package app.model;

public enum Event {
    READ_CONFIG,
    WRITE_CONFIG,
    READ_PETITIONS_FORMED,
    READ_PETITIONS_APPROVED,
    READ_CATALOGS,
    READ_HOLIDAYS,
    WRITE_CATALOGS,
    WRITE_HOLIDAYS,
    COUNT,
}
